server:
  port: 8050
spring:
  application:
    name: user
  datasource:
    name: orderingsystem
    url: jdbc:mysql://106.54.198.161:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456wenxin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.webwork.POJO