server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/versionwen/orderingsystem1.git #git仓库地址
          searchPaths: config #仓库路径
          username: scwswx@gmail.com #git仓库用户名
          password: www.ks5U.com #git仓库密码
      label: master #仓库的分支
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/